default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DATABASE_POOL_SIZE'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
